### ISSUE TITLE
Send Reminder if Timesheet Not Filled or Less Than 8 Hours Logged

### ISSUE THREAD

**Issue by KanchanChauhan** [rtCamp/frappe-slack-connector#21]
Check if team members have filled their timesheet for the previous working day. If a timesheet is incomplete or if logged hours are less than 8, and `Send previous day reminder to fill the timesheet` is checked on Slack Settings, send a reminder with the following message:
"You tracked only {{no of hours}} yesterday. Please fill in your timesheet."

Conditions to check:
- If the timesheet is not filled for the previous working day.
- If the total logged working hours for the previous day is less than 8.

**Comment by ananyo141** [comment]
As discussed with @niraj2477, we have to
- Using an email template in Slack Settings to get the notification format
- Checking user permissions with `.get_list()` and get details like Project, Task for user

**Comment by ananyo141** [comment]
This has been deployed to production.
