### ISSUE TITLE
Slack Settings: Reminder and Notification for Timesheet

### ISSUE THREAD

**Issue by KanchanChauhan** [rtCamp/frappe-slack-connector#22]
**New Section: Timesheet Notifications**

- [x] Send previous day reminder to fill the timesheet
_Enable sending a reminder if a team member hasn’t filled in their timesheet for the previous working day or has logged less than 8 hours._

- [ ] Send notification on Timesheet submitted for Approval
_Enable sending a notification when a timesheet is submitted for approval._

**Comment by ananyo141** [comment]
![Screenshot 2024-10-01 at 3 42 07 PM](https://github.com/user-attachments/assets/6be586dd-cc17-4682-98c0-c819e38431ef)
