### ISSUE TITLE
Slack Connector QA v0

### ISSUE THREAD

**Issue by zeel-codder** [rtCamp/frappe-slack-connector#33]
**Need to test given function with and without our apps**

- [x] Slack sync of user is working or not (Need to create user meta if not exists)
- [x] Leave creation for `Is Leave Without Pay` is working or not
- [x] Leave creation for `Leave With Pay` is working or not
- [x] The leave update are sent to given Slack channel or not
- [x] Error log are generated or not for any failure
- [x] App is working on both installations with and without rtCamp apps (hrms_enhancer, rtcamp, github_connector, etc)

**App version for which need to test** 

- [x] HRMS: version-15 

@ananyo141

**Comment by ananyo141** [comment]
The app has been internally tested by @zeel-codder @Aryan20 and @ananyo141
