### ISSUE TITLE
Rename ERP-Slack-Connector and Add ERPNext Document Link for Easy Application Access

### ISSUE THREAD

**Issue by KanchanChauhan** [rtCamp/frappe-slack-connector#42]
- [x] Rename `ERP-Slack-Connector` to `ERPNext` 
- [x] Include an ERPNext document link below the reason, allowing anyone to easily access and view the application directly in ERPNext.

**Comment by ananyo141** [comment]
<img width="729" alt="Screenshot 2024-09-30 at 6 11 36 PM" src="https://github.com/user-attachments/assets/6dd34fc8-1830-45fb-9414-aee0f5ea2892">

![Screenshot 2024-09-30 at 6 11 44 PM](https://github.com/user-attachments/assets/5800da8a-b83a-4e13-aded-b01f5aa7d302)

The buttonless Leave Application Approve and Notification looks like this
