### ISSUE TITLE
Add a slash command to make timesheet entries from Slack

### ISSUE THREAD

**Issue by ananyo141** [rtCamp/frappe-slack-connector#46]
Introduce a slash command to enable users to open up a form similar to `/apply-leave` and make time entries

**Comment by KanchanChauhan** [comment]
Done
![Image](https://github.com/user-attachments/assets/8e4a61ae-9b41-40bb-8ae9-231dc01a047f)
![Image](https://github.com/user-attachments/assets/128b56a7-8e9d-44c2-85fa-339ffb278cba)
