### ISSUE TITLE
Leave Approver Name field is blank

### ISSUE THREAD

**Issue by KanchanChauhan** [rtCamp/frappe-slack-connector#64]
There is a Leave Approver Name field on Leave Application which gets fetched and set based on Leave Approver. However, when we create Leave Application from Slack, it is blank.

**Created from Desk:**
<img width="627" alt="Screenshot 2024-11-05 at 11 25 17 AM" src="https://github.com/user-attachments/assets/0a0f79d3-c3fb-4b1e-80f0-a745f0100bd4">

**Created from Slack:**
<img width="506" alt="Screenshot 2024-11-05 at 11 26 57 AM" src="https://github.com/user-attachments/assets/63b4f7a8-2385-450f-8e17-389873f0107d">

**Comment by niraj2477** [comment]
@KanchanChauhan   Afaik this field is set via the JS, this can core contribution to set it in controller if it is blank.
